//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Compiler.rc
//
#define IDC_MYICON                      2
#define IDOK2                           3
#define ID_APPLY_NOW                    3
#define IDD_COMPILER_DIALOG             102
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_COMPILER                    109
#define IDR_MAINFRAME                   128
#define IDR_SPG2                        128
#define IDD_PROJECT_DLG                 129
#define IDD_DIALOG1                     131
#define IDD_STAT_DLG                    131
#define IDD_PREVIEW_DLG                 132
#define IDD_INFO_DLG                    134
#define IDR_WORLD_INI                   135
#define IDI_COMPILER                    140
#define IDI_RED_LIGHT                   141
#define IDI_GREEN_LIGHT                 143
#define IDI_ICON1                       146
#define IDI_SHRUB_ACTIVE                146
#define IDI_SHRUB_INACTIVE              153
#define IDI_IM                          154
#define IDI_MP                          155
#define IDI_SM                          156
#define IDR_TEXT1                       158
#define IDR_ACCELERATOR1                160
#define IDR_BZ21                        162
#define IDR_SPG                         162
#define IDR_SPH                         164
#define IDD_PREFERENCES                 165
#define IDI_TRIANGLE                    167
#define IDD_MAP_MANAGER                 173
#define IDR_TEXT2                       175
#define IDR_WORLDS_LIST                 175
#define IDR_SURIVAL_SPG                 177
#define IDR_SURVIVAL_SPG                177
#define IDR_BZ22                        178
#define IDB_PREVIEW                     180
#define IDB_BITMAP1                     181
#define IDB_STATS                       181
#define IDB_INFO                        182
#define IDR_BZ23                        185
#define IDR_BZ24                        186
#define IDR_SURFACE                     196
#define IDR_WORLDS_LIST_2               199
#define IDD_PROJECT_SETTINGS            200
#define IDR_SURFACE_TX                  201
#define IDR_SKY_TX                      202
#define IDR_EVMP                        203
#define IDC_COMBO1                      1000
#define IDC_MAP_SIZE                    1000
#define IDC_LIGHTING                    1000
#define IDC_LOCATION_LIST               1000
#define IDC_MAP_NAME                    1001
#define IDC_AVE_HEIGHT                  1004
#define IDC_AVE_COLOR                   1005
#define IDC_AVE_COLOUR                  1005
#define IDC_MAP_POWER_X                 1006
#define IDC_MAP_POWER_Y                 1007
#define IDC_ZERO_PLAST                  1008
#define IDC_ZERO_PLAST_SPIN             1010
#define IDC_BUTTON1                     1011
#define IDC_FOG_COLOR                   1011
#define IDC_ZERO_PLAST_COLOUR_BTN       1011
#define IDC_FOG_COLOUR                  1011
#define IDC_DELETE_MAP                  1011
#define IDC_FOG_END                     1012
#define IDC_FOG_START                   1013
#define IDC_SP1_X                       1014
#define IDC_SP1_X_SPIN                  1015
#define IDC_SP1_Y                       1016
#define IDC_EDIT1                       1016
#define IDC_ZERO_PLAST_OPACITY          1016
#define IDC_LOCATION_Y                  1016
#define IDC_SP1_Y_SPIN                  1017
#define IDC_SPIN1                       1017
#define IDC_ZERO_PLAST_OPACITY_SPIN     1017
#define IDC_LOCATION_Y_SPIN             1017
#define IDC_SP2_X                       1018
#define IDC_EDIT2                       1018
#define IDC_LOD                         1018
#define IDC_LOCATION_X                  1018
#define IDC_SP2_X_SPIN                  1019
#define IDC_SPIN2                       1019
#define IDC_LOCATION_X_SPIN             1019
#define IDC_SP2_Y                       1020
#define IDC_SP2_Y_SPIN                  1021
#define IDC_SP3_X                       1022
#define IDC_SP3_X_SPIN                  1023
#define IDC_SP3_Y                       1024
#define IDC_SP3_Y_SPIN                  1025
#define IDC_SP4_X                       1026
#define IDC_SP4_X_SPIN                  1027
#define IDC_SP4_Y                       1028
#define IDC_SP4_Y_SPIN                  1029
#define IDC_SP0_X                       1030
#define IDC_SP0_X_SPIN                  1031
#define IDC_SP0_Y                       1032
#define IDC_SP0_Y_SPIN                  1033
#define IDC_FOG_COLOUR_BTN              1034
#define IDC_ZERO_PLAST_COLOUR           1035
#define IDC_MAP_LIST                    1037
#define IDC_TEXTURE_COLOUR_SPEED        1040
#define IDC_TEXTURE_COLOUR_QUALITY      1041
#define IDC_CUSTOM_HARDNESS             1043
#define IDC_CUSTOM_ZERO_LAYER           1044
#define IDC_CUSTOM_SURFACE              1045
#define IDC_CUSTOM_SKY                  1046
#define IDC_DISPLAY_TEXTURE             1047
#define IDC_DISPLAY_HARDNESS            1048
#define IDC_CUSTOM_SKY2                 1048
#define IDC_CUSTOM_SCRIPT               1048
#define IDC_DISPLAY_ZERO_LAYER          1049
#define ID_FILE_OPENPROJECT             32772
#define ID_FILE_SAVEPROJECT             32773
#define ID_FILE_PACKSHRUB               32774
#define ID_FILE_UNPACKSHRUB             32775
#define ID_FILE_INSTALLSHRUB            32776
#define ID_FILE_PROJECTSETTINGS         32777
#define ID_Menu                         32778
#define ID_FILE_NEWPROJECT              32780
#define ID_FILE_MANAGEMAPS              32792
#define ID_TOOLS_PREFERENCES            32797
#define ID_TOOLS_SAVETHUMBNAIL          32800
#define ID_PANEL_WND_0                  32801
#define ID_PANEL_WND_1                  32802
#define ID_PANEL_WND_2                  32803
#define ID_TOOLS_IMPORTSCRIPT           32803
#define ID_PANEL_WND_3                  32804
#define ID_PANEL_WND_4                  32805
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
